export const personal = {
  name: "Cristopher Martínez",
  title: "Junior Full-Stack Developer",
  photo: "/img/FotoCristopher.jpg",
  email: "dannym2407@gmail.com",
  location: "Guatemala, Guatemala",
  age: "18 años",
  available: true,
  yearsCoding: "3+",
  education: "Fundación Kinal · 2026",
  phrase: "Código que transforma ideas en soluciones.",
  bio: "Junior Full-Stack Developer enfocado en backend con C# .NET y Node.js. Me gusta construir APIs limpias, bien documentadas y seguras. Actualmente profundizando en arquitectura de software y patrones de diseño.",
  goals: "Busco crecer como Junior Full-Stack, dominar arquitecturas sólidas y contribuir a proyectos que resuelvan problemas reales.",
  linkedin: "https://www.linkedin.com/in/daniel-mart%C3%ADnez-9182933b6/",
  github: "https://github.com/cmartinez-2024032",
  computrabajo: "https://www.computrabajo.com.gt",
};

export const skills = [
  { name: "JavaScript", level: 85, category: "Frontend", color: "#F7DF1E" },
  { name: "TypeScript", level: 65, category: "Frontend", color: "#3178C6" },
  { name: "React", level: 80, category: "Frontend", color: "#61DAFB" },
  { name: "React Native", level: 70, category: "Frontend", color: "#61DAFB" },
  { name: "Tailwind CSS", level: 85, category: "Frontend", color: "#06B6D4" },
  { name: "HTML5 / CSS3", level: 88, category: "Frontend", color: "#E34F26" },
  { name: "Node.js", level: 80, category: "Backend", color: "#339933" },
  { name: "Express", level: 80, category: "Backend", color: "#000000" },
  { name: "C# .NET", level: 70, category: "Backend", color: "#512BD4" },
  { name: "Java", level: 55, category: "Backend", color: "#ED8B00" },
  { name: "Python", level: 50, category: "Backend", color: "#3776AB" },
  { name: "PostgreSQL", level: 75, category: "Database", color: "#4169E1" },
  { name: "MongoDB", level: 70, category: "Database", color: "#47A248" },
  { name: "MySQL", level: 72, category: "Database", color: "#4479A1" },

  { name: "Git", level: 80, category: "DevOps", color: "#F05032" },
  { name: "Docker", level: 55, category: "DevOps", color: "#2496ED" },
  { name: "CI/CD", level: 50, category: "DevOps", color: "#2088FF" },
];

export const education = [
  { id: 1, title: "Perito en Desarrollo de Software", institution: "Fundación Kinal", year: "2024 - 2026", type: "education", description: "Formación técnica integral en programación Full-Stack y bases de datos." },
];

export const experience = [
  { id: 1, title: "Desarrollador Full-Stack Freelance", company: "Proyectos Personales", period: "2025 - Presente", description: "Desarrollo de aplicaciones web completas con React, Node.js, PostgreSQL, MongoDB. APIs REST, integración con servicios cloud." },
  { id: 2, title: "Desarrollador Backend .NET", company: "AuthService", period: "2026", description: "Implementación de servicios de autenticación JWT con C# .NET, arquitectura limpia y Entity Framework para gestión de usuarios y roles." },
  { id: 3, title: "Prácticas Pre-Profesionales", company: "Fundación Kinal", period: "2026", description: "Desarrollo de plataformas como Kinal Gourmet (gestión restaurantes) y otros proyectos institucionales. Metodologías ágiles, trabajo en equipo." },
];

export const projects = [
  {
    id: 1,
    title: "Kinal Gourmet House",
    shortDesc: "Sistema de gestión de restaurantes con autenticación JWT",
    description: "Plataforma integral para gestión de restaurantes con autenticación por roles, API REST completa, panel de administración y frontend moderno. Implementa JWT, Express, y base de datos relacional.",
    tech: ["JavaScript", "Node.js", "Express", "JWT", "React", "Tailwind CSS", "PostgreSQL"],
    features: [
      "Autenticación multi-rol con JWT",
      "CRUD completo de platos, pedidos y usuarios",
      "Panel de administración con estadísticas",
      "API RESTful documentada",
      "Gestión de inventario y comandas",
      "Arquitectura modular",
    ],
    skills: "Node.js, Express, JWT, autenticación, CRUD, REST API, PostgreSQL",
    github: "https://github.com/cmartinez-2024032/Kinal-Gourmet",
    live: null,
    category: "fullstack",
    year: "2026",
    featured: true,
    hasScreenshots: true,
    screenshots: [
      "/img/projects/kinal-gourmet/01-landing.png",
      "/img/projects/kinal-gourmet/02-menu.png",
      "/img/projects/kinal-gourmet/03-login.png",
      "/img/projects/kinal-gourmet/04-admin-panel.png",
      "/img/projects/kinal-gourmet/05-restaurantes.png",
    ],
  },
  {
    id: 2,
    title: "Página Kinal",
    shortDesc: "Sitio web estático replicando y mejorando la página de Kinal",
    description: "Sitio web estático de varias páginas (fútbol, biografía personal y página de la Fundación Kinal) construido desde cero con HTML y CSS puros, con galería de imágenes, animaciones de entrada y diseño responsive.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    features: [
      "Múltiples páginas navegables (inicio, biografía, Kinal)",
      "Galería de imágenes con overlays",
      "Animaciones de entrada por sección",
      "Maquetación responsive con tarjetas",
      "Diseño replicando la identidad visual de Kinal",
    ],
    skills: "HTML semántico, CSS moderno, maquetación responsive, diseño de UI",
    github: "https://github.com/cmartinez-2024032/PaginaKinal2026",
    live: null,
    category: "frontend",
    year: "2026",
    featured: true,
    hasScreenshots: true,
    screenshots: [
      "/img/projects/pagina-kinal/04-kinal.png",
      "/img/projects/pagina-kinal/01-inicio.png",
      "/img/projects/pagina-kinal/02-galeria.png",
      "/img/projects/pagina-kinal/03-biografia.png",
      "/img/projects/pagina-kinal/05-kinal-detalle.png",
    ],
  },
  {
    id: 3,
    title: "Juego del Ahorcado",
    shortDesc: "Juego del ahorcado web con login, base de datos y temporizador",
    description: "Juego del ahorcado con pantalla de inicio de sesión, palabras y pistas gestionadas desde una base de datos MySQL, temporizador, control de intentos y modal de derrota. Backend con Servlets Java y frontend con JSP y JavaScript.",
    tech: ["Java", "Servlets", "JSP", "JavaScript", "MySQL", "CSS"],
    features: [
      "Inicio de sesión validado contra base de datos",
      "Palabras y pistas aleatorias desde MySQL",
      "Temporizador y control de intentos",
      "Animación progresiva del ahorcado según errores",
      "Modal de derrota con la palabra revelada",
    ],
    skills: "Java, Servlets, JSP, JDBC, MySQL, lógica de juego en JavaScript",
    github: "https://github.com/cmartinez-2024032/ProyectoFinalAhorcado",
    live: null,
    category: "fullstack",
    year: "2025",
    featured: true,
    hasScreenshots: true,
    screenshots: [
      "/img/projects/ahorcado/02-juego.png",
      "/img/projects/ahorcado/01-login.png",
      "/img/projects/ahorcado/03-progreso.png",
      "/img/projects/ahorcado/04-perdiste.png",
    ],
  },
  {
    id: 4,
    title: "ReactNative",
    shortDesc: "Aplicación móvil multiplataforma con React Native",
    description: "Aplicación móvil desarrollada con React Native para múltiples plataformas. Implementa componentes reutilizables, navegación y consumo de APIs REST.",
    tech: ["JavaScript", "React Native", "React", "CSS"],
    features: [
      "Componentes reutilizables",
      "Navegación entre pantallas",
      "Consumo de APIs REST",
      "Interfaz adaptativa multiplataforma",
    ],
    skills: "React Native, desarrollo móvil, consumo de APIs, componentes reutilizables",
    github: "https://github.com/cmartinez-2024032/ReactNative",
    live: null,
    category: "frontend",
    year: "2026",
    featured: false,
    hasScreenshots: true,
    screenshots: [
      "/img/projects/react-native/01-home.png",
    ],
  },
  {
    id: 5,
    title: "AgendaWeb",
    shortDesc: "Agenda de contactos con organización por categorías",
    description: "Aplicación web de agenda para gestionar contactos, organizados por categorías y con interfaz limpia y responsive.",
    tech: ["HTML", "CSS", "JavaScript"],
    features: [
      "Gestión de contactos por categorías",
      "Interfaz limpia y responsive",
      "Búsqueda y filtrado de contactos",
      "Diseño profesional",
    ],
    skills: "HTML semántico, CSS moderno, JavaScript vanilla, responsive design",
    github: "https://github.com/cmartinez-2024032/AgendaWeb-2024032",
    live: null,
    category: "frontend",
    year: "2026",
    featured: false,
    hasScreenshots: true,
    screenshots: [
      "/img/projects/agenda-web/01-login.png",
      "/img/projects/agenda-web/02-contactos.png",
      "/img/projects/agenda-web/03-favoritos.png",
      "/img/projects/agenda-web/04-perfil.png",
      "/img/projects/agenda-web/05-nuevo-contacto.png",
    ],
  },
];
