export const personal = {
  name: "Cristopher Martínez",
  title: "Full-Stack Developer",
  photo: "/img/FotoCristopher.jpg",
  email: "cmartinez054@gmail.com",
  location: "Guatemala, Guatemala",
  age: "18 años",
  available: true,
  yearsCoding: "3+",
  education: "Fundación Kinal · 2026",
  phrase: "Código que transforma ideas en soluciones.",
  bio: "Desarrollador Full-Stack enfocado en backend con C# .NET y Node.js. Me gusta construir APIs limpias, bien documentadas y seguras. Actualmente profundizando en arquitectura de software y patrones de diseño.",
  goals: "Busco crecer como ingeniero de software, dominar arquitecturas distribuidas y contribuir a proyectos que resuelvan problemas reales.",
  linkedin: "https://linkedin.com/in/cmartinez",
  github: "https://github.com/cmartinez-2024032",
  computrabajo: "https://www.computrabajo.com.gt",
};

export const skills = [
  { name: "JavaScript", level: 85, category: "Frontend", color: "#F7DF1E" },
  { name: "TypeScript", level: 65, category: "Frontend", color: "#3178C6" },
  { name: "React", level: 80, category: "Frontend", color: "#61DAFB" },
  { name: "React Native", level: 70, category: "Frontend", color: "#61DAFB" },
  { name: "Tailwind CSS", level: 85, category: "Frontend", color: "#06B6D4" },
  { name: "HTML5 / CSS3", level: 88, category: "Frontend", color: "#E34F26" },
  { name: "Node.js", level: 80, category: "Backend", color: "#339933" },
  { name: "Express", level: 80, category: "Backend", color: "#000000" },
  { name: "C# .NET", level: 70, category: "Backend", color: "#512BD4" },
  { name: "Java", level: 55, category: "Backend", color: "#ED8B00" },
  { name: "Python", level: 50, category: "Backend", color: "#3776AB" },
  { name: "Socket.io", level: 60, category: "Backend", color: "#010101" },
  { name: "PostgreSQL", level: 75, category: "Database", color: "#4169E1" },
  { name: "MongoDB", level: 70, category: "Database", color: "#47A248" },
  { name: "MySQL", level: 72, category: "Database", color: "#4479A1" },
  { name: "SQLite", level: 60, category: "Database", color: "#003B57" },

  { name: "Git", level: 80, category: "DevOps", color: "#F05032" },
  { name: "Docker", level: 55, category: "DevOps", color: "#2496ED" },
  { name: "CI/CD", level: 50, category: "DevOps", color: "#2088FF" },
];

export const education = [
  { id: 1, title: "Perito en Desarrollo de Software", institution: "Fundación Kinal", year: "2024 - 2026", type: "education", description: "Formación técnica integral en programación Full-Stack y bases de datos." },
];

export const experience = [
  { id: 1, title: "Desarrollador Full-Stack Freelance", company: "Proyectos Personales", period: "2025 - Presente", description: "Desarrollo de aplicaciones web completas con React, Node.js, PostgreSQL, MongoDB. APIs REST, integración con servicios cloud." },
  { id: 2, title: "Desarrollador Backend .NET", company: "AuthService", period: "2026", description: "Implementación de servicios de autenticación JWT con C# .NET, arquitectura limpia y Entity Framework para gestión de usuarios y roles." },
  { id: 3, title: "Prácticas Pre-Profesionales", company: "Fundación Kinal", period: "2026", description: "Desarrollo de plataformas como Kinal Gourmet (gestión restaurantes) y otros proyectos institucionales. Metodologías ágiles, trabajo en equipo." },
];

export const projects = [
  {
    id: 1,
    title: "Kinal Gourmet House",
    shortDesc: "Sistema de gestión de restaurantes con autenticación JWT",
    description: "Plataforma integral para gestión de restaurantes con autenticación por roles, API REST completa, panel de administración y frontend moderno. Implementa JWT, Express, y base de datos relacional.",
    tech: ["JavaScript", "Node.js", "Express", "JWT", "React", "Tailwind CSS", "PostgreSQL"],
    features: [
      "Autenticación multi-rol con JWT",
      "CRUD completo de platos, pedidos y usuarios",
      "Panel de administración con estadísticas",
      "API RESTful documentada",
      "Gestión de inventario y comandas",
      "Arquitectura modular",
    ],
    skills: "Node.js, Express, JWT, autenticación, CRUD, REST API, PostgreSQL",
    github: "https://github.com/cmartinez-2024032/Kinal-Gourmet",
    live: null,
    category: "fullstack",
    year: "2026",
    featured: true,
    hasScreenshots: false,
  },
  {
    id: 2,
    title: "AuthService",
    shortDesc: "Servicio de autenticación JWT en C# .NET con Clean Architecture",
    description: "Servicio backend de autenticación desarrollado en C# .NET con Entity Framework. Implementa registro de usuarios, login con JWT, roles, y arquitectura limpia por capas.",
    tech: ["C#", ".NET 8", "Entity Framework", "JWT", "MySQL", "Swagger"],
    features: [
      "Registro y autenticación de usuarios",
      "JWT con refresh tokens",
      "Roles y permisos diferenciados",
      "Arquitectura limpia (capas separadas)",
      "Documentación Swagger/OpenAPI",
      "Validación de datos robusta",
    ],
    skills: "C# .NET, Clean Architecture, JWT, Entity Framework, seguridad backend",
    github: "https://github.com/cmartinez-2024032/AuthService",
    live: null,
    category: "backend",
    year: "2026",
    featured: true,
    hasScreenshots: false,
  },
  {
    id: 3,
    title: "GestorDeOpiniones",
    shortDesc: "Red social de opiniones con interacciones entre usuarios",
    description: "Sistema de gestión de opiniones similar a redes sociales. Implementa autenticación de usuarios, publicaciones con interacciones y comentarios. Base de datos MySQL con esquema relacional.",
    tech: ["JavaScript", "MySQL", "HTML", "CSS", "Bootstrap", "Express"],
    features: [
      "Autenticación y perfiles de usuario",
      "Publicaciones con interacción de usuarios",
      "Sistema de comentarios anidados",
      "Base de datos relacional optimizada",
      "Interfaz responsive con Bootstrap",
    ],
    skills: "CRUD completo, modelado de datos relacionales, Bootstrap, Node.js",
    github: "https://github.com/cmartinez-2024032/GestorDeOpiniones",
    live: null,
    category: "fullstack",
    year: "2026",
    featured: true,
    hasScreenshots: false,
  },
  {
    id: 4,
    title: "ReactNative",
    shortDesc: "Aplicación móvil multiplataforma con React Native",
    description: "Aplicación móvil desarrollada con React Native para múltiples plataformas. Implementa componentes reutilizables, navegación y consumo de APIs REST.",
    tech: ["JavaScript", "React Native", "React", "CSS"],
    features: [
      "Componentes reutilizables",
      "Navegación entre pantallas",
      "Consumo de APIs REST",
      "Interfaz adaptativa multiplataforma",
    ],
    skills: "React Native, desarrollo móvil, consumo de APIs, componentes reutilizables",
    github: "https://github.com/cmartinez-2024032/ReactNative",
    live: null,
    category: "frontend",
    year: "2026",
    featured: false,
    hasScreenshots: false,
  },
  {
    id: 5,
    title: "AgendaWeb",
    shortDesc: "Agenda de contactos con organización por categorías",
    description: "Aplicación web de agenda para gestionar contactos, organizados por categorías y con interfaz limpia y responsive.",
    tech: ["HTML", "CSS", "JavaScript"],
    features: [
      "Gestión de contactos por categorías",
      "Interfaz limpia y responsive",
      "Búsqueda y filtrado de contactos",
      "Diseño profesional",
    ],
    skills: "HTML semántico, CSS moderno, JavaScript vanilla, responsive design",
    github: "https://github.com/cmartinez-2024032/AgendaWeb-2024032",
    live: null,
    category: "frontend",
    year: "2026",
    featured: false,
    hasScreenshots: false,
  },
];
