export const mockPersonal = {
  name: "Cristopher Martínez",
  title: "Junior Full-Stack Developer",
  phrase: "El único límite es el que tú mismo te pongas.",
  location: "Guatemala, Guatemala",
  age: "18 años",
  education: "Fundación Kinal · 2026",
  email: "dannym2407@gmail.com",
  github: "https://github.com/cmartinez-2024032",
  linkedin: "https://www.linkedin.com/in/daniel-mart%C3%ADnez-9182933b6/",
  available: true,
  yearsCoding: 3,
  bio: "Junior Full-Stack Developer apasionado por construir experiencias digitales completas.",
  goals: "Mi objetivo es crecer como Junior Full-Stack y dominar arquitectura backend.",
};

export const mockSkills = [
  { name: "JavaScript", level: 85, category: "Frontend", color: "#f7df1e" },
  { name: "React", level: 80, category: "Frontend", color: "#61dafb" },
  { name: "Node.js", level: 78, category: "Backend", color: "#339933" },
  { name: "PostgreSQL", level: 70, category: "Database", color: "#4169e1" },
  { name: "Python", level: 60, category: "Backend", color: "#3776ab" },
  { name: "Docker", level: 50, category: "DevOps", color: "#2496ed" },
];

export const mockProjects = [
  {
    id: 1,
    title: "Kinal Gourmet House",
    category: "fullstack",
    shortDesc: "Sistema de gestión de restaurantes.",
    description: "Sistema con autenticación JWT y API REST.",
    tech: ["Node.js", "Express", "React", "PostgreSQL"],
    features: ["Autenticación JWT", "CRUD", "Panel admin"],
    github: "https://github.com/cmartinez-2024032/Kinal-Gourmet",
    live: null,
    year: 2026,
    featured: true,
    hasScreenshots: false,
  },
  {
    id: 2,
    title: "AuthService",
    category: "backend",
    shortDesc: "Servicio de autenticación C# .NET.",
    description: "Backend con JWT y Clean Architecture.",
    tech: ["C#", ".NET", "Entity Framework"],
    features: ["JWT Auth", "Clean Architecture"],
    github: "https://github.com/cmartinez-2024032/AuthService",
    live: null,
    year: 2026,
    featured: true,
    hasScreenshots: false,
  },
  {
    id: 3,
    title: "GestorDeOpiniones",
    category: "fullstack",
    shortDesc: "Red social de opiniones.",
    description: "Sistema con autenticación y comentarios.",
    tech: ["Node.js", "Express", "MySQL", "Bootstrap"],
    features: ["Autenticación", "Comentarios"],
    github: "https://github.com/cmartinez-2024032/GestorDeOpiniones",
    live: null,
    year: 2026,
    featured: false,
    hasScreenshots: false,
  },
];
